### ISSUE TITLE
Crash in http server end point handling

### ISSUE THREAD

**Issue by yasharya1984** [gin-gonic/gin#1040]
I have a application which is using gin for http server handling.  I have registered multiple end points. Some time i get "404 page not found" for one of the end point.  I do not see any other in logs.  I have to restart my application to make it work again.   Some time my application crashing with following backtace.

```
|goroutine 109 [running]:
|net/http.(*conn).serve.func1(0xc420576c00)
|	/usr/lib/golang/src/net/http/server.go:1491 +0x12a
|panic(0x7562a0, 0xc42000c1a0)
|	/usr/lib/golang/src/runtime/panic.go:458 +0x243
|encoding/json.(*encodeState).marshal.func1(0xc42033b8e0)
|	/usr/lib/golang/src/encoding/json/encode.go:272 +0x1b9
|panic(0x7562a0, 0xc42000c1a0)
|	/usr/lib/golang/src/runtime/panic.go:458 +0x243
|encoding/json.(*structEncoder).encode(0xc4201f80c0, 0xc4201924d0, 0x789d20, 0xc420016690, 0x199, 0x100)
|	/usr/lib/golang/src/encoding/json/encode.go:601 +0x24e
|encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4201924d0, 0x789d20, 0xc420016690, 0x199, 0xc420010100)
|	/usr/lib/golang/src/encoding/json/encode.go:615 +0x64
|encoding/json.(*ptrEncoder).encode(0xc420048118, 0xc4201924d0, 0x750d40, 0xc420016690, 0x16, 0x750100)
|	/usr/lib/golang/src/encoding/json/encode.go:742 +0xe3
|encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4201924d0, 0x750d40, 0xc420016690, 0x16, 0xc420010100)
|	/usr/lib/golang/src/encoding/json/encode.go:747 +0x64
|encoding/json.(*encodeState).reflectValue(0xc4201924d0, 0x750d40, 0xc420016690, 0x16, 0x100)
|	/usr/lib/golang/src/encoding/json/encode.go:307 +0x82
|encoding/json.(*encodeState).marshal(0xc4201924d0, 0x750d40, 0xc420016690, 0x100, 0x0, 0x0)
|	/usr/lib/golang/src/encoding/json/encode.go:280 +0xb8
|encoding/json.(*Encoder).Encode(0xc42033b978, 0x750d40, 0xc420016690, 0x7fee465ee240, 0xc420192420)
|	/usr/lib/golang/src/encoding/json/stream.go:193 +0x8e
|github.com/gin-gonic/gin/render.jsonRender.Render(0x7fee465ee208, 0xc420192420, 0xc8, 0xc420545330, 0x1, 0x1, 0xc420183a00, 0x7fee465ee208)
|	github.com/gin-gonic/gin/render/render.go:60 +0xfa
|github.com/gin-gonic/gin/render.(*jsonRender).Render(0xb897f8, 0x7fee465ee208, 0xc420192420, 0xc8, 0xc420545330, 0x1, 0x1, 0xc420192401, 0xb897f8)
|	<autogenerated>:2 +0x8b
|github.com/gin-gonic/gin.(*Context).Render(0xc420192420, 0xc8, 0xb54060, 0xb897f8, 0xc420545330, 0x1, 0x1)
|	github.com/gin-gonic/gin/context.go:322 +0xba
|github.com/gin-gonic/gin.(*Context).JSON(0xc420192420, 0xc8, 0x750d40, 0xc420016690)
|	github.com/gin-gonic/gin/context.go:331 +0xc7
```

**Comment by appleboy** [comment]
Please post your example code.

**Comment by javierprovecho** [comment]
@yasharya1984 

you may get 404 if requests are made using wrong method and [`*engine.HandleMethodNotAllowed` (default: false)](https://github.com/gin-gonic/gin/blob/master/gin.go#L76) is not set to true

on the other hand, the stack trace shows a json encode panic, maybe you are trying to render a struct with an interface o nil pointer, i can't tell until you show us your code or the panic msg error.

closing, reopen when you post the requirements 😃
