### ISSUE TITLE
Panic if using copied context for streaming

### ISSUE THREAD

**Issue by cunnutamatri** [gin-gonic/gin#1763]
- go version: 1.10
- gin version (or commit ref): 1.3.0
- operating system:debian

## Description

Hi, I get the following crash if I use a copied context (inside a goroutine) and I try to start a .Stream command:

> panic: interface conversion: interface is nil, not http.CloseNotifier
> 
> goroutine 63 [running]:
> github.com/gin-gonic/gin.(*responseWriter).CloseNotify(0xc0000ccbb0, 0x100010000)
> 	/home/pippus/gocode/pkg/mod/github.com/gin-gonic/gin@v1.3.0/response_writer.go:108 +0x43
> github.com/gin-gonic/gin.(*Context).Stream(0xc0000ccbb0, 0xc000144fa0)
> 	/home/pippus/gocode/pkg/mod/github.com/gin-gonic/gin@v1.3.0/context.go:823 +0x42

It looks like this is because the Copy function nullifies the ResponseWriter used by the stream.

How should this work? It is possible to use context.Stream inside a goroutine?

Thanks in advance for your time.

**Comment by palvarezcordoba** [comment]
Writing into a Writer from a goroutine does not seems safe. https://www.reddit.com/r/golang/comments/3xpzom/are_the_write_funcs_in_iowritecloser_goroutinesafe/

**Comment by palvarezcordoba** [comment]
Why do you need to write from a goroutine? Maybe you could do something like this: https://github.com/drone/drone/blob/master/server/stream.go
