### ISSUE TITLE
Context.FileAttachment gives panic when unit testing

### ISSUE THREAD

**Issue by jessequinn** [gin-gonic/gin#2691]
## Description

I have written a unit test for a specific controller:

```
package controllers

import (
	"context"
	"downloads-api-golang/configs/general"
	"downloads-api-golang/internal/httputil"
	"downloads-api-golang/internal/repositories"
	"downloads-api-golang/internal/services"
	"github.com/gin-contrib/cache/persistence"
	"github.com/gin-gonic/gin"
	"github.com/koding/logging"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
)

type getObjectServiceMock struct {
	handleGetObjectFn func() (*os.File, *string, error)
}

func (mock getObjectServiceMock) HandleGetObject(ctx *context.Context, vars *general.Config, oci *repositories.OCI, mysql *repositories.Repository, req *httputil.GetObjectRequestParameter, query *httputil.GetObjectRequestQuery) (*os.File, *string, error) {
	return mock.handleGetObjectFn()
}

type validateRequestsGetObjectServiceMock struct {
	handleValidateRequestsFn func() (*httputil.GetObjectRequestParameter, *httputil.GetObjectRequestQuery, error)
}

func (mock validateRequestsGetObjectServiceMock) HandleValidateRequestsGetObject(c *gin.Context) (*httputil.GetObjectRequestParameter, *httputil.GetObjectRequestQuery, error) {
	return mock.handleValidateRequestsFn()
}

func TestMain(m *testing.M) {
	db, err := gorm.Open(mysql.Open(general.DbURL(general.BuildDBConfig())), &gorm.Config{})
	if err != nil {
		logging.Fatal(err.Error())
	}
	repo := repositories.NewRepository(db)
	if err := repo.Migrate(); err != nil {
		logging.Fatal(err.Error())
	}
	exitVal := m.Run()
	os.Exit(exitVal)
}

func TestGetObject(t *testing.T) {
	gin.SetMode(gin.TestMode)

	var (
		ctx   *context.Context
		oci   *repositories.OCI
		redis *persistence.RedisStore
	)

	r := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(r)
	getObjectServiceMock := getObjectServiceMock{}
	getObjectServiceMock.handleGetObjectFn = func() (*os.File, *string, error) {
		tmpFile, err := ioutil.TempFile(os.TempDir(), "downloads-api-")
		if err != nil {
			return nil, nil, err
		}

		if _, err := tmpFile.WriteString("text to append\n"); err != nil {
			return nil, nil, err
		}

		ext := ".jpg"

		return tmpFile, &ext, nil
	}
	services.GetObjectService = getObjectServiceMock
	validateRequestsServiceMock := validateRequestsGetObjectServiceMock{}
	validateRequestsServiceMock.handleValidateRequestsFn = func() (*httputil.GetObjectRequestParameter, *httputil.GetObjectRequestQuery, error) {
		return &httputil.GetObjectRequestParameter{ID: 123123123}, &httputil.GetObjectRequestQuery{Downloader: 213123213}, nil
	}
	services.ValidateRequestsGetObjectService = validateRequestsServiceMock
	vars := general.New()
	db, err := gorm.Open(mysql.Open(general.DbURL(general.BuildDBConfig())), &gorm.Config{})
	if err != nil {
		logging.Fatal(err.Error())
	}
	repo := repositories.NewRepository(db)
	if err := repo.Migrate(); err != nil {
		logging.Fatal(err.Error())
	}

	c.Set("ctx", ctx)
	c.Set("vars", vars)
	c.Set("oci", oci)
	c.Set("mysql", repo)
	c.Set("redis", redis)

	GetObject(c)

	if r.Code != http.StatusOK {
		t.Error("response code should be 200")
	}
}
```
The controller:
```
package controllers

import (
	"downloads-api-golang/internal/helpers"
	"downloads-api-golang/internal/httputil"
	"downloads-api-golang/internal/services"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/koding/logging"
	"io/ioutil"
	"net/http"
	"os"
)

// GetObject godoc
// @Summary Sends specific entity.
// @Description sends specific entity.
// @Param id path int true "downloads_id"
// @Param downloader query int true "downloader"
// @Accept json
// @Produce json
// @Success 200 file file
// @Failure 400 {object} httputil.HTTPError
// @Router /api/v1/downloads/object/{id} [get]
func GetObject(c *gin.Context) {
	ctx, vars, oci, mysql, _, err := helpers.RetrieveConnections(c)
	if err != nil {
		logging.Error(err.Error())
		httputil.NewError(c, http.StatusInternalServerError, err) // TODO: implement custom error msg
		return
	}
	// Validation service
	getObjectRequestParameter, getObjectRequestQuery, err := services.ValidateRequestsGetObjectService.HandleValidateRequestsGetObject(c)
	if err != nil {
		logging.Error(err.Error())
		httputil.NewError(c, http.StatusBadRequest, err) // TODO: implement custom error msg
		return
	}
	// Get object service
	tmpFile, ext, err := services.GetObjectService.HandleGetObject(ctx, vars, oci, mysql, getObjectRequestParameter, getObjectRequestQuery)
	if err != nil {
		logging.Error(err.Error())
		httputil.NewError(c, http.StatusInternalServerError, err) // TODO: implement custom error msg
		return
	}
	defer func(name string) {
		err := os.Remove(name)
		if err != nil {
			logging.Error(err.Error())
			httputil.NewError(c, http.StatusInternalServerError, err) // TODO: implement custom error msg
			return
		}
	}(tmpFile.Name())

	file, err := os.Open(tmpFile.Name())
	if err != nil {
		logging.Error(err.Error())
		httputil.NewError(c, http.StatusInternalServerError, err) // TODO: implement custom error msg
		return
	}
	defer func() {
		if err = file.Close(); err != nil {
			logging.Error(err.Error())
			httputil.NewError(c, http.StatusInternalServerError, err) // TODO: implement custom error msg
			return
		}
	}()

	b, _ := ioutil.ReadAll(file)
	fmt.Printf("contents: %s\n", b)

	// Generally forces a file download rather than appearing in the browser.
	c.FileAttachment(tmpFile.Name(), fmt.Sprintf("tmp%s", *ext))
}
```
All mocking appears to be working; however, I receive a panic:
```
--- FAIL: TestGetObject (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6f3fc6]

goroutine 7 [running]:
testing.tRunner.func1.1(0xb8a520, 0x113a0d0)
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000194a80)
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1075 +0x41a
panic(0xb8a520, 0x113a0d0)
	/home/jessequinn/sdk/go1.15.3/src/runtime/panic.go:969 +0x1b9
net/http.ServeFile(0x7f5264854c98, 0xc00048a000, 0x0, 0xc0002cd1a0, 0x1c)
	/home/jessequinn/sdk/go1.15.3/src/net/http/fs.go:678 +0x26
github.com/gin-gonic/gin.(*Context).FileAttachment(0xc00048a000, 0xc0002cd1a0, 0x1c, 0xc0004a1020, 0x7)
	/home/jessequinn/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:967 +0x1f2
downloads-api-golang/internal/controllers.GetObject(0xc00048a000)
	/home/jessequinn/Desktop/flowti/test/go/downloads-api-golang/internal/controllers/get_object_controller.go:73 +0x4be
downloads-api-golang/internal/controllers.TestGetObject(0xc000194a80)
	/home/jessequinn/Desktop/flowti/test/go/downloads-api-golang/internal/controllers/get_object_controller_test.go:98 +0x655
testing.tRunner(0xc000194a80, 0xc8bed0)
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1168 +0x2b3


Process finished with the exit code 1
```
on the final line `c.FileAttachment(tmpFile.Name(), fmt.Sprintf("tmp%s", *ext))`

Any ideas what i am doing wrong here?

## How to reproduce

```
package main

import (
	"github.com/gin-gonic/gin"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
)

func main() {
	g := gin.Default()
	g.GET("/download", Download)
	g.Run(":9000")
}

func Download(c *gin.Context) {
	tmpFile, err := ioutil.TempFile(os.TempDir(), "downloads-api-")
	if err != nil {
		c.JSON(http.StatusInternalServerError, err)
		return
	}
	if _, err := tmpFile.WriteString("text to append\n"); err != nil {
		c.JSON(http.StatusInternalServerError, err)
		return
	}
	defer func(name string) {
		err := os.Remove(name)
		if err != nil {
			c.JSON(http.StatusInternalServerError, err)
			return
		}
	}(tmpFile.Name())
	c.FileAttachment(tmpFile.Name(), "tmp.jpg")
}

func TestDownload(t *testing.T) {
	gin.SetMode(gin.TestMode)

	r := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(r)
	
	Download(c)

	if r.Code != http.StatusOK {
		t.Error("response code should be 200")
	}
}
```

## Expectations

```
$ curl http://localhost:9000/download
file downloads
```

## Actual result

```
$ curl -i http://localhost:9000/download

--- FAIL: TestGetObject (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6f3fc6]

goroutine 7 [running]:
testing.tRunner.func1.1(0xb8a520, 0x113a0d0)
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc000194a80)
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1075 +0x41a
panic(0xb8a520, 0x113a0d0)
	/home/jessequinn/sdk/go1.15.3/src/runtime/panic.go:969 +0x1b9
net/http.ServeFile(0x7f5264854c98, 0xc00048a000, 0x0, 0xc0002cd1a0, 0x1c)
	/home/jessequinn/sdk/go1.15.3/src/net/http/fs.go:678 +0x26
github.com/gin-gonic/gin.(*Context).FileAttachment(0xc00048a000, 0xc0002cd1a0, 0x1c, 0xc0004a1020, 0x7)
	/home/jessequinn/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:967 +0x1f2
downloads-api-golang/internal/controllers.GetObject(0xc00048a000)
	/home/jessequinn/Desktop/flowti/test/go/downloads-api-golang/internal/controllers/get_object_controller.go:73 +0x4be
downloads-api-golang/internal/controllers.TestGetObject(0xc000194a80)
	/home/jessequinn/Desktop/flowti/test/go/downloads-api-golang/internal/controllers/get_object_controller_test.go:98 +0x655
testing.tRunner(0xc000194a80, 0xc8bed0)
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/home/jessequinn/sdk/go1.15.3/src/testing/testing.go:1168 +0x2b3


Process finished with the exit code 1


```

## Environment

- go version: go version go1.15.3 linux/amd64
- gin version (or commit ref): 	github.com/gin-gonic/gin v1.6.3
- operating system: 20.04.2 LTS (Focal Fossa)

**Comment by myml** [comment]
The context returned by CreateTestContext has no request.
Add `httptest.NewRequest(http.MethodGet, "/ping", nil)` to context.
```go
func TestDownload(t *testing.T) {
	gin.SetMode(gin.TestMode)

	r := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(r)
	c.Request = httptest.NewRequest(http.MethodGet, "/ping", nil)
	
	Download(c)

	if r.Code != http.StatusOK {
		t.Error("response code should be 200")
	}
}
```

**Comment by twocs** [comment]
Further to this, the panic on error in httptest.NewRequest is a design feature, not a bug.
https://pkg.go.dev/net/http/httptest#NewRequest
> NewRequest panics on error for ease of use in testing, where a panic is acceptable.
