### ISSUE TITLE
panic: context: internal error: missing cancel error

### ISSUE THREAD

**Issue by wxning1107** [gin-gonic/gin#2808]
## Description

panic: context: internal error: missing cancel error

goroutine 39124 [running]:
context.(*cancelCtx).cancel(0xc000b408a0, 0xaac800, 0x0, 0x0)
        /usr/local/go/src/context/context.go:396 +0x2bb
context.(*timerCtx).cancel(0xc000b408a0, 0x0, 0x0, 0x0)
        /usr/local/go/src/context/context.go:479 +0x4a
context.propagateCancel.func1(0x212c5c0, 0xc000bf64a0, 0x20fff98, 0xc000b408a0)
        /usr/local/go/src/context/context.go:281 +0x115
created by context.propagateCancel
        /usr/local/go/src/context/context.go:278 +0x1fb

## Environment

- go version: 1.16
- gin version (or commit ref): 1.7.1
- operating system: linux

**Comment by wxning1107** [comment]
It's similar to #1731, but it's occurred again, How to avoid this bug?
