### ISSUE TITLE
"panic: runtime error: invalid memory address or nil pointer dereference" when used in a gorouting for paho.mqtt

### ISSUE THREAD

**Issue by Ks89** [gin-gonic/gin#2875]
## Description

I'm creating an API server with gin with a POST API (json body) to publish a paho.mqtt message and respond back with "200" if there aren't errors.

POST request -> gin API server -> publish paho.mqtt -> send mqtt message to destination -> return http 200 ok
 
As suggested on the doc I copied the gin context with `cCp := c.Copy()` and then used cCp to send a responde `cCp.JSON(...)`

## How to reproduce

```
package main
import (
	"fmt"
	mqtt "github.com/eclipse/paho.mqtt.golang"
	"github.com/gin-gonic/gin"
	"net/http"
)
var mqttClient mqtt.Client
func main() {
	mqttClient = mqtt.NewClient(mqtt.NewClientOptions().AddBroker("tcp://127.0.0.1:1883").SetClientID("apiServer"))
	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	router := gin.Default()
	router.POST("/sendtomqtt", func (c *gin.Context) {
		// create copy to be used inside the goroutine
		cCp := c.Copy()
		t := mqttClient.Publish("test/test2", 0, false, "testtesttest")
		go func() {
			_ = t.Wait()
			if t.Error() != nil {
				fmt.Println(t.Error()) // Use your preferred logging technique (or just fmt.Printf)
			} else {
				cCp.JSON(http.StatusOK, gin.H{"message": "sent"})
			}
		}()
	})
	err := router.Run(":8081")
	if err != nil {
		panic(err)
	}
}
```

## Expectations

gin server should't crash with a POST request, even if used to call a mqtt server

## Actual result

```
[GIN-debug] POST   /sendtomqtt               --> main.main.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8081

[GIN] 2021/09/18 - 14:24:41 | 200 |      16.877µs | 192.168.178.128 | POST     "/sendtomqtt"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x131df49]

goroutine 35 [running]:
github.com/gin-gonic/gin.(*responseWriter).Header(0xc00018ce00)
	<autogenerated>:1 +0x29
github.com/gin-gonic/gin/render.writeContentType({0x1d15f70, 0xc00018ce00}, {0x168a770, 0x1, 0x1})
	/Users/ks89/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/render.go:36 +0x3a
github.com/gin-gonic/gin/render.WriteJSON({0x1d15f70, 0xc00018ce00}, {0x136c980, 0xc000090bd0})
	/Users/ks89/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:68 +0x4c
github.com/gin-gonic/gin/render.JSON.Render(...)
	/Users/ks89/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/render/json.go:55
github.com/gin-gonic/gin.(*Context).Render(0xc00018ce00, 0xc8, {0x144b680, 0xc000094380})
	/Users/ks89/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:913 +0xe7
github.com/gin-gonic/gin.(*Context).JSON(...)
	/Users/ks89/go/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:956
main.main.func1.1()
	/Users/ks89/git/gin-with-mqtt/main.go:24 +0x13a
created by main.main.func1
	/Users/ks89/git/gin-with-mqtt/main.go:19 +0xc8
exit status 2
```

## Environment

- go version: 1.17
- gin version (or commit ref): 1.7.4
- operating system: macOS BigSur 11.6
- github.com/eclipse/paho.mqtt.golang version: 1.3.5

**Comment by thinkgos** [comment]
why not use sync.WaitGroup or chan ? 
because c.Copy, not copy ResponseWriter, it is nil.

**Comment by Ks89** [comment]
Hi!
Oh, I totally missed this `because c.Copy, not copy ResponseWriter`. Good to know.

I'm still learning go and in particular topics like concurrency.

I used that technique because suggested directly by the developers of paho.mqtt in their readme [HERE](https://github.com/eclipse/paho.mqtt.golang/blob/master/README.md#error-handling)

Do you have suggestion of how to refactor that small piece of code in a better way to bypass this problem?

thank u.

**Comment by Ks89** [comment]
My current version is this one with `select`. It seems to be ok:

```
package main
import (
	"fmt"
	mqtt "github.com/eclipse/paho.mqtt.golang"
	"github.com/gin-gonic/gin"
	"net/http"
)
var mqttClient mqtt.Client
func main() {
	mqttClient = mqtt.NewClient(mqtt.NewClientOptions().AddBroker("tcp://127.0.0.1:1883").SetClientID("apiServer"))
	if token := mqttClient.Connect(); token.Wait() && token.Error() != nil {
		panic(token.Error())
	}
	router := gin.Default()
	router.POST("/sendtomqtt", func (c *gin.Context) {
		t := mqttClient.Publish("test/test2", 0, false, "testtesttest")

	        select {
	        case <- t.Done():
		        if t.Error() != nil {
			        fmt.Println("Error")
			        fmt.Println(t.Error())
		        } else {
			        fmt.Println("sending response")
			        c.JSON(http.StatusOK, gin.H{"message": "sent"})
		        }
	        }
	})
	err := router.Run(":8081")
	if err != nil {
		panic(err)
	}
}
```

I'm not sure if there is a better/cleaner implementation. 
I'm open to suggestions.
